[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=86400"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=86400"
[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, s-max-age=86400"
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, s-max-age=86400"
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"